# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'Supplier' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Supplier
  pod 'MLKitVision', '~> 8.0.0'
  
  pod_target_xcconfig = {
    'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64'
  }
  
  user_target_xcconfig = {
    'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64'
  }

end
